### ISSUE TITLE
Navbar and Footer section enhancement

### ISSUE THREAD

**Issue by kedar1998** [SrijanShovit/carbonops-v2#47] opened 2023-05-30 04:40 UTC
Navbar and footer is having unnecessary height. I would like to work on this issue. Can you please assign it to me under GSSOC'23.

## Navbar
![image](https://github.com/SrijanShovit/carbonops-v2/assets/103363619/6aaa7589-dc1b-4102-bb88-a95d2846e237)

## Footer
![image](https://github.com/SrijanShovit/carbonops-v2/assets/103363619/76a0a542-ef55-4942-b198-7683c3c7f336)

**Comment by kedar1998** [comment] 2023-05-30 04:41
I will also make it responsive for all screen sizes.

**Comment by shreya024** [comment] 2023-05-30 16:35
> I will also make it responsive for all screen sizes.

@kedar1998 Assigned! Go for it

**Comment by MahendraDani** [comment] 2023-05-31 09:37
> @shreya024 @kedar1998 I have checked on my local system. The `navbar` is fully responsive for all views and does not have height as given in your screenshot.
> 
> Regarding the `footer section` you can make its width as 100% so that it occupies entire viewport.

@shreya024 Would you please check on your local system and confirm that `navbar` is properly functioning?
What are your views about the width of the `footer` section?

**Comment by MahendraDani** [comment] 2023-05-31 09:44
@kedar1998 Please make sure that you always make a pull from remote repo so that your local repo is even with the remote upstream.

You can follow the below steps:

1. Set the upstream
```
git remote add upstream https://github.com/SrijanShovit/carbonops-v2.git
```

2. Check the links of `upstream` and `origin`:
```
git remote -v
```

3. Take a pull from upstream/main branch
```
git fetch --all
```

4. Reset your local main branch to the upstream/main branch
```
git reset --hard upstream/main
```

5. Push the changes to your origin
```
git push origin main
```

If you perform all the above steps correctly, the following should be shown on your forked repo-
![p](https://github.com/SrijanShovit/carbonops-v2/assets/116940083/9ce2b052-f216-46e5-8ea0-ac794282e5e2)

Now you can start working on the project!

> The alternative command for steps 4 and 5 is ```git pull upstream main```.

Please let me know if you have any more doubts!

**Comment by kedar1998** [comment] 2023-05-31 12:21
You can see live website. You will see that issue

**Comment by shreya024** [comment] 2023-05-31 14:13
@MahendraDani The issue is visible on the hosted site and not on local.and thereby assigned to @kedar1998

**Comment by MahendraDani** [comment] 2023-05-31 14:14
@shreya024 Would you please provide the link of the hosted site?

**Comment by MahendraDani** [comment] 2023-05-31 14:15
> @shreya024 Would you please provide the link of the hosted site?

No need to share the link I found it myself!

**Comment by shreya024** [comment] 2023-05-31 14:16
> @shreya024 Would you please provide the link of the hosted site?
> 

It's in the repo in the Environments section Production and Preview

**Comment by MahendraDani** [comment] 2023-05-31 14:18
> > @shreya024 Would you please provide the link of the hosted site?
> 
> It's in the repo in the Environments section Production and Preview

@shreya024 I found the link, thanks!

**Comment by kedar1998** [comment] 2023-06-01 10:50
I have raised PR. Please review and let me know anything I need to change or update.

**Comment by shreya024** [comment] 2023-06-14 04:52
> I have raised PR. Please review and let me know anything I need to change or update.

Unassigned since PR has unresolved conflicts

**Comment by Ujwal19k** [comment] 2023-06-14 17:10
Can you assign this to me under GSSOC. I had raised an issue today #105

**Comment by mandliyarajendra11** [comment] 2023-06-20 08:10
this is is still open 
@shreya024  can you assign me this issue

**Comment by MAYANKpandey14** [comment] 2023-06-24 13:09
Hey, I would like work on this issue under GSSoC 23

**Closed** 2023-07-02 05:06 UTC
Labels: bug, gssoc23, level1
