### ISSUE TITLE
Tailwind CSS logo in Readme

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/carbonops-v2#2] opened 2023-05-14 15:35 UTC
Add Tailwind CSS logo in Readme appropriately under Tech Stacks section

**Comment by alokmishra70** [comment] 2023-05-14 16:56
Assign this issue to me

**Comment by SrijanShovit** [comment] 2023-05-14 17:14
ok sure
However, I am waiting for this project to be accepted for GSSOC '23

**Comment by Tushar98644** [comment] 2023-05-19 18:55
i would like to work for it under GSSOC'23 @SrijanShovit

**Comment by nwokporochukwuebuka** [comment] 2023-05-20 04:40
Good morning, I have seen the issue and as a beginner in open source I'd appreciate it if this issue can be given to me.

**Comment by SrijanShovit** [comment] 2023-05-21 10:42
@alokmishra70 Have you attempted the task? If no, I would merge someone else's PR for this issue.

**Comment by Rutujeet** [comment] 2023-05-22 03:12
I kindly request your consideration in assigning Issue #2 under GSSOC'23 to me.

**Comment by iusamahub** [comment] 2023-05-23 13:42
Hey @SrijanShovit I've made a pull request for this issue. please merge it. Thanks

**Comment by shreya024** [comment] 2023-05-23 16:03
> Hey @SrijanShovit I've made a pull request for this issue. please merge it. Thanks



> I kindly request your consideration in assigning Issue #2 under GSSOC'23 to me.

@Rutujeet Assigning this to u

**Comment by shreya024** [comment] 2023-05-23 16:04
> Hey @SrijanShovit I've made a pull request for this issue. please merge it. Thanks

Hey @iusamahub Kindly wait till the issue is assigned to you next time since it is done on a first come first serve basis.Thanks

**Closed** 2023-05-28 01:55 UTC
Labels: good first issue, readme, GSSOC
